export const template = {
  tracks: [
    {
      id: "track_captions_1777958817890_qljiyzin7",
      name: "Caption Track",
      type: "Caption",
      clipIds: ["clip_1777958823050_nsmiav8hs", "clip_1777958823053_nxj0fh9gd"],
    },
    {
      id: "track_video_1777958817890_s754rzcbk",
      name: "Main Footage",
      type: "Video",
      clipIds: [
        "clip_1777958818858_fhf1jzj4l",
        "clip_1777958819718_phbhukwo5",
        "clip_1777958820445_3ym21001s",
      ],
    },
    {
      id: "track_audio_1777958817890_8zn2tvxbe",
      name: "Audio Track",
      type: "Audio",
      clipIds: ["clip_1777958822048_gabeca6iq"],
    },
  ],
  clips: [
    {
      type: "Image",
      src: "https://cdn.scenify.io/VIDEOS/cJpj4IZm7_QGZg_UMyz4m/cJpj4IZm7_QGZg_UMyz4m-seg-0/IMAGE/GSP0QqjQh0.png",
      display: {
        from: 0,
        to: 760000,
      },
      playbackRate: 1,
      duration: 760000,
      left: 0,
      top: -7.5,
      width: 1080,
      height: 1935,
      angle: 0,
      zIndex: 10,
      opacity: 1,
      flip: null,
      style: {},
      trim: {
        from: 0,
        to: 0,
      },
      id: "clip_1777958818858_fhf1jzj4l",
      animations: [
        {
          type: "comboRightDistort",
          options: {
            duration: 760000,
            delay: 0,
            easing: "linear",
            iterCount: 1,
            id: "animation_3l74g5w",
          },
          params: {
            "0%": {
              scale: 3,
              angle: -15,
              blur: 5,
              mirror: 1,
            },
            "40%": {
              blur: 1,
              angle: -6,
              scale: 1.5,
              mirror: 1,
            },
            "60%": {
              blur: 0,
              angle: 0,
              scale: 1,
              mirror: 1,
            },
            "70%": {
              blur: 0,
              angle: 0,
              scale: 1,
              mirror: 1,
            },
            "85%": {
              scale: 0.95,
              mirror: 1,
            },
            "100%": {
              scale: 0.8,
              mirror: 1,
            },
            presetParams: {},
          },
        },
      ],
      effects: [],
    },
    {
      type: "Image",
      src: "https://cdn.scenify.io/VIDEOS/cJpj4IZm7_QGZg_UMyz4m/cJpj4IZm7_QGZg_UMyz4m-seg-0/IMAGE/0CeWERvNdL.png",
      display: {
        from: 760000,
        to: 1560000,
      },
      playbackRate: 1,
      duration: 800000,
      left: 0,
      top: -7.5,
      width: 1080,
      height: 1935,
      angle: 0,
      zIndex: 10,
      opacity: 1,
      flip: null,
      style: {},
      trim: {
        from: 0,
        to: 0,
      },
      id: "clip_1777958819718_phbhukwo5",
      animations: [
        {
          type: "comboZoom2",
          options: {
            duration: 800000,
            delay: 0,
            easing: "linear",
            iterCount: 1,
            id: "animation_fiai3is",
          },
          params: {
            "0%": {
              scale: 0.7,
              motionBlur: 8,
              angle: 0,
              mirror: 1,
            },
            "30%": {
              scale: 1,
              motionBlur: 0,
              angle: 0,
              mirror: 1,
            },
            "60%": {
              scale: 1,
              motionBlur: 0,
              angle: 0,
              mirror: 1,
            },
            "100%": {
              scale: 0.7,
              motionBlur: 8,
              angle: 0,
              mirror: 1,
            },
            presetParams: {},
          },
        },
      ],
      effects: [],
    },
    {
      type: "Image",
      src: "https://cdn.scenify.io/VIDEOS/cJpj4IZm7_QGZg_UMyz4m/cJpj4IZm7_QGZg_UMyz4m-seg-0/IMAGE/UUmgjnPfV4.png",
      display: {
        from: 1560000,
        to: 3043000,
      },
      playbackRate: 1,
      duration: 1483000,
      left: 0,
      top: -7.5,
      width: 1080,
      height: 1935,
      angle: 0,
      zIndex: 10,
      opacity: 1,
      flip: null,
      style: {},
      trim: {
        from: 0,
        to: 0,
      },
      id: "clip_1777958820445_3ym21001s",
      animations: [
        {
          type: "comboWobble",
          options: {
            duration: 1483000,
            delay: 0,
            easing: "linear",
            iterCount: 1,
            id: "animation_1rwqv0b",
          },
          params: {
            "0%": {
              scale: 1.2,
              angle: 15,
              x: -400,
              blur: 5,
              mirror: 1,
            },
            "6%": {
              scale: 1,
              mirror: 1,
              angle: 0,
              blur: 0,
              x: 0,
            },
            "18%": {
              scale: 1,
              mirror: 1,
              angle: -10,
              x: -100,
            },
            "30%": {
              angle: -10,
              scale: 1,
              mirror: 1,
              x: 0,
            },
            "35%": {
              angle: 0,
              scale: 1,
              mirror: 1,
              x: 0,
            },
            "45%": {
              angle: 5,
              scale: 1,
              mirror: 1,
              x: 0,
            },
            "55%": {
              angle: 0,
              scale: 1,
              mirror: 1,
              x: 0,
            },
            "60%": {
              angle: 0,
              scale: 1,
              mirror: 1,
              blur: 0,
              x: 0,
            },
            "100%": {
              scale: 2.5,
              blur: 5,
              mirror: 1,
            },
            presetParams: {},
          },
        },
      ],
      effects: [],
    },
    {
      type: "Audio",
      src: "https://cdn.scenify.io/VIDEOS/cJpj4IZm7_QGZg_UMyz4m/cJpj4IZm7_QGZg_UMyz4m-seg-0/AUDIO/TtzJbh1nVZ.mp3",
      display: {
        from: 200000,
        to: 2943000,
      },
      playbackRate: 1,
      duration: 2743000,
      left: 0,
      top: 0,
      width: 0,
      height: 0,
      angle: 0,
      zIndex: 30,
      opacity: 1,
      flip: null,
      style: {},
      trim: {
        from: 0,
        to: 2743000,
      },
      loop: false,
      id: "clip_1777958822048_gabeca6iq",
      volume: 1,
    },
    {
      type: "Caption",
      src: "",
      display: {
        from: 200000,
        to: 1799999.9000000001,
      },
      playbackRate: 1,
      duration: 1599999.9000000001,
      left: 168.5,
      top: 1470,
      width: 743,
      height: 168,
      angle: 0,
      zIndex: 20,
      opacity: 1,
      flip: null,
      style: {
        fontSize: 64,
        fontFamily: "Proxima-Nova",
        fontWeight: "700",
        fontStyle: "normal",
        color: "#000000",
        align: "center",
        fontUrl: "https://cdn.subgen.co/FONTS/proxima-nova-semibold.ttf",
        stroke: {
          color: "transparent",
          width: 0,
        },
        shadow: {
          color: "#000000",
          alpha: 0.5,
          blur: 4,
          distance: 0,
          angle: 0,
        },
      },
      trim: {
        from: 0,
        to: 0,
      },
      text: "Most people\nhave parasites and",
      caption: {
        words: [
          {
            text: "Most",
            from: 0,
            to: 320,
            isKeyWord: true,
            paragraphIndex: "",
          },
          {
            text: "people",
            from: 320,
            to: 560,
            isKeyWord: false,
            paragraphIndex: "",
          },
          {
            text: "have",
            from: 560,
            to: 799.99995,
            isKeyWord: false,
            paragraphIndex: "",
          },
          {
            text: "parasites",
            from: 799.99995,
            to: 1360,
            isKeyWord: false,
            paragraphIndex: "",
          },
          {
            text: "and",
            from: 1360,
            to: 1599.9999,
            isKeyWord: true,
            paragraphIndex: "",
          },
        ],
        colors: {
          appeared: "#000000",
          active: "#000000",
          activeFill: "transparent",
          background: "#ffffff",
          keyword: "transparent",
        },
        preserveKeywordColor: true,
        positioning: {
          videoWidth: 1080,
          videoHeight: 1920,
        },
        textBoxStyle: {
          style: "tiktok",
          textAlign: "center",
          maxLines: 2,
          borderRadius: 20,
          horizontalPadding: 20,
          verticalPadding: 20,
        },
      },
      textBoxStyle: {
        style: "tiktok",
        textAlign: "center",
        maxLines: 2,
        borderRadius: 20,
        horizontalPadding: 20,
        verticalPadding: 20,
      },
      id: "clip_1777958823050_nsmiav8hs",
      effects: [],
      mediaId: "clip_1777958820445_3ym21001s",
    },
    {
      type: "Caption",
      src: "",
      display: {
        from: 1799999.9000000001,
        to: 2520000,
      },
      playbackRate: 1,
      duration: 720000.1,
      left: 255.5,
      top: 1531.5,
      width: 569,
      height: 99,
      angle: 0,
      zIndex: 20,
      opacity: 1,
      flip: null,
      style: {
        fontSize: 64,
        fontFamily: "Proxima-Nova",
        fontWeight: "700",
        fontStyle: "normal",
        color: "#000000",
        align: "center",
        fontUrl: "https://cdn.subgen.co/FONTS/proxima-nova-semibold.ttf",
        stroke: {
          color: "transparent",
          width: 0,
        },
        shadow: {
          color: "#000000",
          alpha: 0.5,
          blur: 4,
          distance: 0,
          angle: 0,
        },
      },
      trim: {
        from: 0,
        to: 0,
      },
      text: "have no clue.",
      caption: {
        words: [
          {
            text: "have",
            from: 0,
            to: 160.00009999999997,
            isKeyWord: true,
            paragraphIndex: "",
          },
          {
            text: "no",
            from: 160.00009999999997,
            to: 400.0001,
            isKeyWord: false,
            paragraphIndex: "",
          },
          {
            text: "clue.",
            from: 400.0001,
            to: 720.0000999999999,
            isKeyWord: true,
            paragraphIndex: "",
          },
        ],
        colors: {
          appeared: "#000000",
          active: "#000000",
          activeFill: "transparent",
          background: "#ffffff",
          keyword: "transparent",
        },
        preserveKeywordColor: true,
        positioning: {
          videoWidth: 1080,
          videoHeight: 1920,
        },
        textBoxStyle: {
          style: "tiktok",
          textAlign: "center",
          maxLines: 2,
          borderRadius: 20,
          horizontalPadding: 20,
          verticalPadding: 20,
        },
      },
      textBoxStyle: {
        style: "tiktok",
        textAlign: "center",
        maxLines: 2,
        borderRadius: 20,
        horizontalPadding: 20,
        verticalPadding: 20,
      },
      id: "clip_1777958823053_nxj0fh9gd",
      effects: [],
      mediaId: "clip_1777958820445_3ym21001s",
    },
  ],
  settings: {
    width: 1080,
    height: 1920,
    fps: 30,
    backgroundColor: "#1c1917",
  },
};
